/**
 * knowledge-ingest — M1/M2 实现。
 *
 * 支持三种模式：
 * - skill:   生成 SKILL.md
 * - plugin:  生成可注入的 DSH 插件骨架
 * - memory:  把研究摘要写入本地研究记忆（后续可接 Agent OS）
 */

export const name = 'knowledge-ingest'
export const inject = ['tools']

import { exec } from 'node:child_process'
import { mkdirSync, writeFileSync, appendFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { homedir } from 'node:os'

function toJsonSchema(spec) {
  const properties = {}
  const required = []
  for (const [key, meta] of Object.entries(spec || {})) {
    const prop = { type: meta.type }
    if (meta.description) prop.description = meta.description
    if (meta.items) prop.items = meta.items
    properties[key] = prop
    if (meta.required) required.push(key)
  }
  return { type: 'object', properties, required, additionalProperties: false }
}

function isValidSkillName(name) {
  return /^[a-z0-9][a-z0-9-]*$/.test(name)
}

function pluginPackageJson(name) {
  return JSON.stringify({
    name,
    version: '0.1.0',
    type: 'module',
    main: './lib/index.mjs',
    exports: { '.': './lib/index.mjs' },
  }, null, 2)
}

function pluginIndex(name, description) {
  return `/**
 * ${name} — generated by knowledge_ingest.
 * ${description || ''}
 */
export const name = '${name}'
export const inject = ['tools']

function retainMemoryAsync(content) {
  return new Promise((resolve) => {
    const args = JSON.stringify({ content: content.slice(0, 2000), client: 'dsh-global-tool-discovery', scope: 'global' })
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
    const cmd = "mcporter call agentos-memory.memory_retain --args \"" + args + "\" --output json"
    exec(cmd, { encoding: 'utf8', timeout: 20000, shell: true }, (error, stdout) => {
      if (error) resolve({ ok: false, output: String(error?.message || error) })
      else resolve({ ok: true, output: stdout })
    })
  })
}

export function apply(ctx) {
  ctx.effect(() => ctx.tools.register({
    name: '${name}_ping',
    description: 'Generated skeleton tool. Replace with real implementation.',
    parameters: { type: 'object', properties: {}, additionalProperties: false },
    output: { schema: { type: 'object', properties: { text: { type: 'string' } }, required: ['text'], additionalProperties: false }, render: (_a, v) => [{ type: 'text', text: v.text }] },
    async execute() {
      return { text: '${name} skeleton is working.' }
    },
  }))
}
`
}

function buildSkillFile(name, description, whenToUse, content, sources) {
  const frontmatter = [
    '---',
    `name: ${name}`,
    `description: ${description}`,
  ]
  if (whenToUse) frontmatter.push(`whenToUse: ${whenToUse}`)
  frontmatter.push('---')

  const body = [content]
  if (sources.length > 0) {
    body.push('\n## Sources')
    for (const src of sources) body.push(`- ${src}`)
  }
  return `${frontmatter.join('\n')}\n\n${body.join('\n')}\n`
}

function retainMemoryAsync(content) {
  return new Promise((resolve) => {
    const args = JSON.stringify({ content: content.slice(0, 2000), client: 'dsh-global-tool-discovery', scope: 'global' })
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
    const cmd = "mcporter call agentos-memory.memory_retain --args \"" + args + "\" --output json"
    exec(cmd, { encoding: 'utf8', timeout: 20000, shell: true }, (error, stdout) => {
      if (error) resolve({ ok: false, output: String(error?.message || error) })
      else resolve({ ok: true, output: stdout })
    })
  })
}

export function apply(ctx) {
  ctx.effect(() => {
    const dispose = ctx.tools.register({
      name: 'knowledge_ingest',
      description: 'Turn research findings into reusable assets. Modes: skill (SKILL.md), plugin (DSH plugin skeleton), memory (research summary).',
      parameters: toJsonSchema({
        mode: { type: 'string', required: false, description: 'skill | plugin | memory (default skill)' },
        name: { type: 'string', required: false, description: 'kebab-case asset name' },
        description: { type: 'string', required: false, description: 'short description' },
        whenToUse: { type: 'string', required: false, description: 'optional when-to-use guidance' },
        content: { type: 'string', required: false, description: 'skill instructions / method / research summary' },
        sources: { type: 'array', required: false, items: { type: 'string' }, description: 'source URLs' },
        pluginRoot: { type: 'string', required: false, description: 'plugin output root (default E:/ai-files/dsh-experimental)' },
        dryRun: { type: 'boolean', required: false, description: 'only preview, do not write' },
        confirm: { type: 'boolean', required: false, description: 'must be true to actually write plugin files' },
      }),
      output: {
        schema: { type: 'object', additionalProperties: false, properties: { text: { type: 'string' } }, required: ['text'] },
        render: (_a, v) => [{ type: 'text', text: v.text }],
      },
      async execute(args, exec) {
        const mode = typeof args.mode === 'string' ? args.mode : 'skill'
        const name = typeof args.name === 'string' ? args.name.trim() : ''
        const description = typeof args.description === 'string' ? args.description.trim() : ''
        const whenToUse = typeof args.whenToUse === 'string' ? args.whenToUse.trim() : ''
        const content = typeof args.content === 'string' ? args.content : ''
        const sources = Array.isArray(args.sources) ? args.sources.filter(s => typeof s === 'string') : []
        const dryRun = args.dryRun === true
        const confirm = args.confirm === true

        if (!isValidSkillName(name)) return { text: `Invalid name "${name}". Use kebab-case.` }

        if (mode === 'skill') {
          if (!description || !content) return { text: 'description and content are required for skill mode.' }
          const root = join(homedir(), '.dsh', 'skills')
          const skillDir = join(root, name)
          const skillFile = join(skillDir, 'SKILL.md')
          try {
            mkdirSync(skillDir, { recursive: true })
            writeFileSync(skillFile, buildSkillFile(name, description, whenToUse, content, sources), 'utf8')
            return { text: `Skill created: ${skillFile}\nVerify with skill_search("${name}") and skill_load("${name}").` }
          } catch (error) {
            return { text: `knowledge_ingest skill failed: ${String((error && error.message) || error)}` }
          }
        }

        if (mode === 'plugin') {
          const root = typeof args.pluginRoot === 'string' && args.pluginRoot.trim()
            ? args.pluginRoot.trim()
            : 'E:/ai-files/dsh-experimental'
          const dir = join(root, name)
          const files = [
            { path: join(dir, 'package.json'), content: pluginPackageJson(name) },
            { path: join(dir, 'lib', 'index.mjs'), content: pluginIndex(name, description) },
          ]
          if (dryRun || !confirm) {
            const list = files.map(f => `- ${f.path}`).join('\n')
            return { text: `Plugin skeleton dry-run for "${name}".\nFiles:\n${list}\n\nPass "confirm": true to write.` }
          }
          try {
            for (const f of files) {
              mkdirSync(dirname(f.path), { recursive: true })
              writeFileSync(f.path, f.content, 'utf8')
            }
            return { text: `Plugin skeleton created at ${dir}.\nNext: dev_inject_plugin({"dir": "${dir}"})` }
          } catch (error) {
            return { text: `knowledge_ingest plugin failed: ${String((error && error.message) || error)}` }
          }
        }

        if (mode === 'memory') {
          if (!content) return { text: 'content is required for memory mode.' }
          const file = join(homedir(), '.dsh', 'research', 'memory.jsonl')
          try {
            mkdirSync(dirname(file), { recursive: true })
            const entry = {
              type: 'research-memory',
              name,
              description,
              summary: content.slice(0, 2000),
              sources,
              createdAt: new Date().toISOString(),
            }
            appendFileSync(file, `${JSON.stringify(entry)}\n`, 'utf8')

            const agentOs = await retainMemoryAsync(content)
            if (agentOs.ok) {
              return { text: `Research memory appended to ${file}\nAgent OS memory_retain: ok\n${agentOs.output.slice(0, 300)}` }
            }
            return { text: `Research memory appended to ${file}\nAgent OS memory_retain failed (fallback local only): ${agentOs.output.slice(0, 200)}` }
          } catch (error) {
            return { text: `knowledge_ingest memory failed: ${String((error && error.message) || error)}` }
          }
        }

        return { text: `Unknown mode "${mode}". Use skill, plugin, or memory.` }
      },
    })
    return dispose
  })
}

